version: "3.8"

services: 
  php: 
    image: kllmkll/glpi:9.5.5
    ports: 
      - "80:80"
      - "443:443"
    networks: 
      - glpi
    depends_on:
      - db
    volumes: 
      - ./src:/var/www/html
  db:
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: change
      MYSQL_USER: glpi
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: glpi
    ports: 
      - "3306:3306"
    networks: 
      - glpi

networks:
  glpi:
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.0.10.0/24
          gateway: 172.0.10.1
